### ISSUE TITLE
[Core] Transition

### ISSUE THREAD

**Issue by e1emeb0t** [eleme/element-react#106]
目前的`Transition`实现遇到一个bug, 如果指定children的key为随机数时, 在某些情况下会重复产生过渡效果, 如果将key设为一个静态值的话, 某些情况下将不会有过渡效果.

@cuining @HopeLyn

**Comment by cuining** [comment]
发现个问题，热更新的时候Transition组件渲染次数太多导致页面崩溃

**Comment by e1emeb0t** [comment]
Fixed by merging: https://github.com/eleme/element-react/pull/105

**Comment by e1emeb0t** [comment]
Remove `<Transition />`
