### ISSUE TITLE
element 官网 移动端适配

### ISSUE THREAD

**Issue by tsix2019** [eleme/element-react#1092]
element官网移动网页端适配问题严重
我怀疑开发者都没有用手机预览过官网
![Screenshot_20210420_235145](https://user-images.githubusercontent.com/59950751/115427183-d1186200-a233-11eb-9842-fc494ca80255.jpg)
虽然一般人不会用手机访问官网，但是你是个做ui库的

**Comment by zhourengui** [comment]
你是来搞笑的吗？
