### ISSUE TITLE
Select组件存在严重的滚动卡顿问题,  通过devtools查看后发现在div.el-select元素上绑定了大量的scroll和resize事件监听器

### ISSUE THREAD

**Issue by allanfish** [eleme/element-react#207]

**Comment by e1emeb0t** [comment]
多谢反馈, 我看一下.

**Comment by e1emeb0t** [comment]
https://github.com/eleme/element-react/pull/208 优化了一下, 减少了一些事件(scroll/resize)绑定, 应该还有改进空间.

**Comment by allanfish** [comment]
我计划在项目中全面使用element-react, 后续有问题我会及时反馈

**Comment by e1emeb0t** [comment]
@allanfish 好的, 这个项目是长期维护的, 饿了么目前也有两个项目使用了`element-react`. 第一版的代码都是从Vue版的`element`拷贝过来的, 后续开发将会脱离`element`, 慢慢改进吧.

这周应该会发布一个版本到npm上, 这样对外部项目会方便一些, 现在你可以`npm i eleme/element-react`.

**Comment by e1emeb0t** [comment]
Closing since I've created a new issue https://github.com/eleme/element-react/issues/222 to track this.
