### ISSUE TITLE
这不是 based on ant design吗。。

### ISSUE THREAD

**Issue by jerrylu0522** [eleme/element-react#234]
这不是 based on ant design。。😂

**Comment by e1emeb0t** [comment]
我想所有的Web UI组件库的祖先都是同一个...🤥

**Comment by jerrylu0522** [comment]
不过UI挺好看的，赞一个👍

**Comment by e1emeb0t** [comment]
这你需要感谢[Element](https://github.com/ElemeFE/element)团队.
