### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by doxiaodong** [eleme/element-react#352]
I'm glad to help

**Comment by e1emeb0t** [comment]
It's a question we had discussed internally, only one of our crews was familiar with Typescript, and it's not me, so we decide to do type check with `flowtype`, the benefit of `flowtype` is it only checks the files start with flow comment, not globally as Typescript.

**Comment by doxiaodong** [comment]
I want to use it at a `typescript+react` based repo. The flow does not help

**Comment by doxiaodong** [comment]
I don't want to add it to `@types/`(as `material-ui`), it's better to host with this repo(as `moment.js`).

**Comment by e1emeb0t** [comment]
We already have integrated `flowtype`, so the file extension can't be changed to `.ts`, do you have any solution? Maybe a pull request?

**Comment by doxiaodong** [comment]
Just add a `index.d.ts` file.  I can do it this weekend.

**Comment by e1emeb0t** [comment]
Yep, `.d.ts` is the better solution that I have discussed with my colleague just now, thanks for your pull request.

**Comment by doxiaodong** [comment]
@e1emeb0t

**Comment by e1emeb0t** [comment]
Sorry for the delay, can your rebase your commits?

**Comment by e1emeb0t** [comment]
Closing since the pull request had been merged.
