### ISSUE TITLE
Found a bug on the documentation demo

### ISSUE THREAD

**Issue by Kulbear** [eleme/element-react#355]
### Description

The behavior I met on the documentation demo is obviously unexpected. See GIF.

### Reproduce Steps

![default](https://cloud.githubusercontent.com/assets/14886380/25933012/4fb1519c-3647-11e7-89ab-11496ddcba47.gif)

### Error Trace (if possible)

Just go [https://eleme.github.io/element-react/#/zh-CN/tag](https://eleme.github.io/element-react/#/zh-CN/tag)

**Comment by e1emeb0t** [comment]
Thanks for your report, I'm looking into now.

**Comment by e1emeb0t** [comment]
Closing this issue since it's been fixed, thanks again.
