### ISSUE TITLE
Time Picker and Date Picker problem

### ISSUE THREAD

**Issue by Raincal** [eleme/element-react#356]
![2017-05-11 05 30 40 pm](https://cloud.githubusercontent.com/assets/6279478/25942583/d7a4bed6-366f-11e7-843a-a44b0b324469.png)

### Description
[在这个页面](https://eleme.github.io/element-react/#/zh-CN/time-picker)
问题1： 选择时间时，滚动到最后，最后一个时间显示不完整
问题2： 触发多个选择器时，之前的不会消失

### 本地环境
macOS Sierra 10.12.4
Chrome 58.0.3029.110

**Comment by inter-action** [comment]
第一个问题 我会找时间处理下 第二个问题 我的想法是每个组件的行为应该是独立的 也就是说一个下拉框的弹出不应该影响另一个下拉框的行为 只允许一个下拉弹窗的行为 可以在外部加一个全局的state

**Comment by Raincal** [comment]
@inter-action 一般都是只允许一个的吧，比如[element vue版](http://element.eleme.io/#/zh-CN/component/time-picker) 和 [antd](https://ant.design/components/time-picker-cn/)

**Comment by inter-action** [comment]
我的主要考虑还是之前的那一点 如果允许一个 就需要组件去感知到另外一个组件 然后通过某种机制去通知他们关闭 而组件打开和关闭应该是属于他们内部自己的状态 也不应该需要知道周围的组件， 至于vue版和antd我就不评论了 他们可能有他们自己的想法

**Comment by chengjianhua** [comment]
@Raincal 我觉得第二个问题确实应该由用户自己决定, 要是用户就是希望打开新的不会关闭之前的呢, 这样自由度更高, 可定制性更强. 如果想要实现这种效果, 可以在此基础上自己再封装一个.
