### ISSUE TITLE
node_modules in package

### ISSUE THREAD

**Issue by thchia** [eleme/element-react#358]
### Description

The package throws this error:
```
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

### Reproduce Steps

Pretty much everywhere when attempting to use this package (in a webpack build)

### Solution

The package is downloading node_modules for some reason, and causing a conflict with my own copy of React.

**Comment by e1emeb0t** [comment]
I install the latest version which is `1.0.0-beta.4`, it looks fine, but yesterday one of my colleagues also found this issue, could you tell me which version of `react` and `webpack` you're using?

**Comment by e1emeb0t** [comment]
You can try to remove `node_modules` completely, then reinstall npm packages.

**Comment by thchia** [comment]
My React is `15.4.2` and webpack is `2.5.0`.

I did try rebuilding node_modules but that didn't work, it still redownloaded `node_modules` into the `element-react` directory.

**Comment by e1emeb0t** [comment]
That's wired, what's the node version you have?

**Comment by thchia** [comment]
Node is `7.9.0`
