### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by xujianhai** [eleme/element-react#367]
### Description

After install the package, I plan to run webpack. there are some errors as follows : 
ERROR in ./~/element-react/dist/npm/src/message/Toast.js
Module not found: Error: Can't resolve 'image-webpack' in '/Users/snow_young/secrect/opensource/d3/demo'
 @ ./~/element-react/dist/npm/src/message/Toast.js 27:11-42
 @ ./~/element-react/dist/npm/src/message/Message.js
 @ ./~/element-react/dist/npm/src/message/index.js
 @ ./~/element-react/dist/npm/src/index.js
 @ ./~/element-react/dist/npm/index.js
 @ ./src/main.js

### Reproduce Steps

1. npm i element-react --save
2. add functions 
import { Button } from 'element-react';
ReactDOM.render(<Button type="primary">Hello</Button>, document.getElementById('example'));
3. run webpack command. and then failed as before.
### Error Trace (if possible)
ERROR in ./~/element-react/dist/npm/src/message/Toast.js
Module not found: Error: Can't resolve 'image-webpack' in '/Users/snow_young/secrect/opensource/d3/demo'
 @ ./~/element-react/dist/npm/src/message/Toast.js 27:11-42
 @ ./~/element-react/dist/npm/src/message/Message.js
 @ ./~/element-react/dist/npm/src/message/index.js
 @ ./~/element-react/dist/npm/src/index.js
 @ ./~/element-react/dist/npm/index.js
 @ ./src/main.js

It's better to post up the error stack for us to trace this issue.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

I need help from yours.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by e1emeb0t** [comment]
Can you provide the `webpack.config.js` and the raw console logs?
