### ISSUE TITLE
There is a css issue in Select component

### ISSUE THREAD

**Issue by jianzhou520** [eleme/element-react#370]
### Description

There is a style issue in Select Component

### Reproduce Steps

1. import Select Component and render then simple component, you will find the last elemtn  in the option list has very limited gap.

### Solution
I guess the "li" elment's paddingBottom attr is effected by his parent element

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![](http://ww1.sinaimg.cn/large/b433dad2gy1ffm7jbsnymj205e03ujr8.jpg)

![](http://ww1.sinaimg.cn/large/b433dad2gy1ffm7kdl5azj206m04dt8j.jpg)

**Comment by e1emeb0t** [comment]
Thanks for your feedback, but the screenshot that you referred is broken.

**Comment by jianzhou520** [comment]
![](http://olifvwe92.bkt.clouddn.com/1494842968%281%29.jpg)
![](http://olifvwe92.bkt.clouddn.com/3TEQHZZ929%5DFI%7D%5BI_SW1G1T.png)

**Comment by e1emeb0t** [comment]
This issue should be fixed by https://github.com/eleme/element-react/pull/373
