### ISSUE TITLE
[Select]: 官网自定义模版demo显示有误

### ISSUE THREAD

**Issue by infeng** [eleme/element-react#384]
### Description

官网Select组件自定义模版demo，选择框里面的城市拼音超出选择框，如图：

![element-bug-1](https://cloud.githubusercontent.com/assets/16483610/26189119/7ed7e31c-3bd5-11e7-85e8-8a99c2bba3f6.png)

**Comment by e1emeb0t** [comment]
你的浏览器是什么?

**Comment by infeng** [comment]
chrome dev最新版

**Comment by e1emeb0t** [comment]
我在稳定版的Chrome上没有看到这个问题, 我会持续关注.
