### ISSUE TITLE
MenuItem this.context.component  undefined

### ISSUE THREAD

**Issue by JQChan** [eleme/element-react#391]
MenuItem this.context.component undefined  And can't find parent.instanceType
![image](https://cloud.githubusercontent.com/assets/7911342/26517533/07b3c7e8-42cd-11e7-89c8-cff366e01592.png)

environment: 
![image](https://cloud.githubusercontent.com/assets/7911342/26517546/460aaeb2-42cd-11e7-829a-8ac8cd97bc88.png)

**Comment by cuining** [comment]
This is IE10 and below issue.
You can read about it [here](http://babeljs.io/docs/usage/caveats/#classes-10-and-below)

**Comment by e1emeb0t** [comment]
@cuining I've modified `.babelrc`, and enabled `loose` for the preset `es2015`, will this fix the issue on IE 10 and below since we don't have Windows PC for testing?

**Comment by e1emeb0t** [comment]
`element-react@1.0.3` should solve this issue, @JQChan can you confirm?

**Comment by rlog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Element React Issues](https://trello.com/c/Aextr5a9/308-element-react-issues)
