### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by msaglietto** [eleme/element-react#398]
### Description

Hello 

I was trying the library and I got an error when it renders on the server .. 

The problem comes in the use of Popper that use windows and document.createElement

What is odd is even including an individual element that should not use Popper  from the es5 lib like:
```
import Button from 'element-react/dist/npm/es5/src/button';
```
It trying to use Popper because the code has a 
```
var _libs = require('../../libs');
```
I guess from 
```
import { Component, PropTypes } from '../../libs';
```

So I was wondering if you are considering add support to server side rendering  and if you know a workaround this so at least some components can be used... 

### Error Trace (if possible)
```
/home/msaglietto/Projects/test/node_modules/element-react/dist/npm/es5/libs/utils/popper.js:44
        module.exports = factory();
                         ^
ReferenceError: window is not defined
    at /home/msaglietto/Projects/test/node_modules/element-react/dist/npm/es5/libs/utils/popper.js:53:16
    at root (/home/msaglietto/Projects/test/node_modules/element-react/dist/npm/es5/libs/utils/popper.js:44:26)
    at Object.<anonymous> (/home/msaglietto/Projects/test/node_modules/element-react/dist/npm/es5/libs/utils/popper.js:49:3)
...
 at Object.<anonymous> (/home/msaglietto/Projects/test/node_modules/element-react/dist/npm/es5/libs/utils/popper-mixins.js:9:15)
```

**Comment by e1emeb0t** [comment]
This maybe related to this closed issue https://github.com/eleme/element-react/issues/241, I think the only solution is upgrading `popper.js` and I did so, but the upgrade action caused another issue, give me some time to fix this.

**Comment by msaglietto** [comment]
Ok thanks you very much for let me know

**Comment by rlog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Element React Issues](https://trello.com/c/Aextr5a9/308-element-react-issues)
