### ISSUE TITLE
Add decription for empty array datasource of Table

### ISSUE THREAD

**Issue by jianzhou520** [eleme/element-react#399]
### Description

Explain the issue you met, and describe what you expected to be. If you can write in English, we will be very grateful.

### Reproduce Steps

1. Set an empty array for Table Component
2. You'll see the table show nothing

### Solution

Add description for Table component when there is no data, it may let users confused. It's a bug or network issue?

### Additional Information

img link http://ww1.sinaimg.cn/large/b433dad2gy1fg6oqkf1jfj21bs0idmxv.jpg

**Comment by e1emeb0t** [comment]
@cuining Awesome!

**Comment by rlog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Element React Issues](https://trello.com/c/Aextr5a9/308-element-react-issues)
