### ISSUE TITLE
[Message box](Demo页面close icon的位置错位)

### ISSUE THREAD

**Issue by phobal** [eleme/element-react#415]
### Description

在[Message](https://eleme.github.io/element-react/#/zh-CN/message-box)demo页面中，关闭按钮的icon错位，跑到左侧来了

<img width="420" alt="2017-06-09 5 37 24" src="https://user-images.githubusercontent.com/9244211/26970095-a5152082-4d3a-11e7-8c52-66d129b716b9.png">

### Additional Information

浏览器版本：
chrome 58.0.3029.110 (64-bit)   
safari 10.0.1 (12602.2.14.0.7)

**Comment by e1emeb0t** [comment]
Thanks for your report, this issue will be fixed in `1.0.7`.
