### ISSUE TITLE
datepicker error   element-react 1.0.9

### ISSUE THREAD

**Issue by munkh-altai** [eleme/element-react#420]
when click clear get error
format.js:38 Uncaught TypeError: Cannot read property 'replace' of undefined
    at _default (format.js:38)

**Comment by inter-action** [comment]
can you check it again, we can't reproduce the error on our offical site. also can you post your environment here, (browser version etc...)?

**Comment by munkh-altai** [comment]
sorry this is my bug. i was't change date format with undefined
