### ISSUE TITLE
Input,Select.. properties are invalid

### ISSUE THREAD

**Issue by cench** [eleme/element-react#422]
### Description

Such as Input,Select .. these component properties are invalid,

I need to defined a  fixed width Select Component

### Reproduce Steps

```
<Select style={{width: '100px'}}>
    ...
</Select>

It doesn't seem possible
```

### Expect

I hope can apply props directly, like using Element-Vue-Ui

**Comment by e1emeb0t** [comment]
Supporting `className` and `style` props is our first priority job, your code worked as expected.

<img width="298" alt="wx20170616-104749 2x" src="https://user-images.githubusercontent.com/21698993/27209902-43860178-5281-11e7-8b7e-904938d18d32.png">
