### ISSUE TITLE
when set default values for select then height is wrong

### ISSUE THREAD

**Issue by munkh-altai** [eleme/element-react#449]
When i set default values for "Combobox multiple" element height is wrong.

**Comment by e1emeb0t** [comment]
Combox?

**Comment by munkh-altai** [comment]
combobox is Select

**Comment by e1emeb0t** [comment]
Have you overridden the css style, maybe the global `select` or `li` tag?

**Comment by munkh-altai** [comment]
no.
if i select one by one it's normal like your demo but when i set default values for Select then input height is wrong

**Comment by e1emeb0t** [comment]
Thanks for your feedback, I'm looking into it.

**Comment by e1emeb0t** [comment]
element-react@1.0.15 has been published into npm, closing this issue since it's been fixed.
