### ISSUE TITLE
请问select如何不通过清除按钮清空选中项

### ISSUE THREAD

**Issue by liuer422** [eleme/element-react#452]
### Description

select如何清空选中项，通过设置select的value为‘’，没有效果

**Comment by e1emeb0t** [comment]
你可以调试看一下Select的value前后是不是都是空字符串'', 导致render没有重新渲染. 我在本地测试通过更改Select的value为'', 是可以清空选中项的.

**Comment by liuer422** [comment]
谢谢e1emeb0t，不知道怎么又好了，可能是设置state没设置对
