### ISSUE TITLE
官网指导写法建议

### ISSUE THREAD

**Issue by wlx200510** [eleme/element-react#476]
### Description

浏览官网上的指导代码发现每次在组件中都要用bind绑定this  对于新手来说看起来有点别扭

### Solution

这种可以替换为在函数定义时用箭头函数的形式 从而继承了this指向
代码更优雅  也符合ES6的最新写法和思路

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by e1emeb0t** [comment]
你的想法是把函数的实现都放到`render`里么? 或者说把caller写到`render`里?

**Comment by wlx200510** [comment]
那样写不是更复杂么  我是建议这样   代码如下：
```constructor(props) {
  super(props);

  this.state = {
    form: {
      user: '',
      region: ''
    }
  };
}

onSubmit = (e) => {
  e.preventDefault();

  console.log('submit!');
}

onChange = (key, value) => {
  this.setState({
    form: Object.assign(this.state.form, { [key]: value })
  });
}
render() {
  return (
      <Form inline={true} model={this.state.form} onSubmit={this.onSubmit} className="demo-form-inline">
...
    </Form>
  )
}
```

**Comment by wlx200510** [comment]
render中的input的写法为`<Input value={this.state.form.user} placeholder="审批人" onChange={(e,value)=>this.onChange('user',value)}></Input>`

**Comment by e1emeb0t** [comment]
但是为了this指针安全, 我个人习惯用`bind`, 因为有些回调函数会改写this, 比如
`Form.props.onSubmit.apply(this, [args])`

**Comment by wlx200510** [comment]
所以要显式确定this指向？ 回调函数在react中都是自己写的 如果有改写  应该也是刻意为之吧

**Comment by e1emeb0t** [comment]
我个人习惯是这样😂, 因为在一些开发过程中总遇到this指针变了, 为了稳妥所以牺牲了一些性能.

**Comment by cuining** [comment]
类似`this.onClick.bind(this)` 以及 `() => this.onClick()`这样的写法存在一个问题，每次触发render，都会返回一个新的函数，导致子节点不得不重新渲染。
用属性初始化的写法则避免了这个问题，而且因为有箭头函数，this指向的都是当前类

**Comment by e1emeb0t** [comment]
`handleClick = () => {}`这种写法毕竟还是试验性的语法, 对于新手来说还需要去理解, 我个人建议还是用bind, 但是考虑到性能, 在构造函数里声明bind函数.

```
class Toggle extends React.Component {
  constructor(props) {
    super(props);
    this.state = {isToggleOn: true};

    // This binding is necessary to make `this` work in the callback
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.setState(prevState => ({
      isToggleOn: !prevState.isToggleOn
    }));
  }

  render() {
    return (
      <button onClick={this.handleClick}>
        {this.state.isToggleOn ? 'ON' : 'OFF'}
      </button>
    );
  }
}

ReactDOM.render(
  <Toggle />,
  document.getElementById('root')
);
```

**Comment by wlx200510** [comment]
[ 掘金上有个总结比较好的文章](https://juejin.im/post/595cbfb15188250d892f6896)   贴出来希望更多人看到，我所在团队用babel直接到了ES6的stage-2特性 所以提议如此 其实在constructor里面进行this绑定对性能也有一定影响  主要还是看团队约定  希望新手看到这里能明白一点this的具体使用策略。
