### ISSUE TITLE
Select and Table component

### ISSUE THREAD

**Issue by nicemayi** [eleme/element-react#477]
Is it possible to use "multiple={ true }"  and "filterable={ true }" inside <Select /> component at the same  time? 
I found out the "type: 'expand'" in the  Table-Column attribute can be ONLY available if I put corresponding column as the first one, is it intended to design like this for some reason? is it possible to use the 'expand' attribute on any other column but the first one?

Thank.

**Comment by e1emeb0t** [comment]
Notice: this project is `element-react`, I assume you're using `element-ui`.

1. `multiple` and `filterable` can be applied at the same time to `Select`.
2. According to `element-react` document, I didn't find the `expand` type of Table Column right now.
