### ISSUE TITLE
Form表单验证不支持异步校验

### ISSUE THREAD

**Issue by liuer422** [eleme/element-react#478]
### Description

表单的某一字段需要进行ajax请求校验时，不能正确显示错误提示信息。
`rules: {
    name: [{ 
                    required: true, message: '请输入名称', trigger: 'blur' 
                },{ 
                    validator: (rule, value, callback) => {                                             
                      if (value === '') {
                        callback(new Error('请输入名称'));
                      } else {
                        Service.checkNameExist(value).then((response)=>{
                            if(response.status == 200 && response.data.rel == 1){                                
                                callback(new Error('名称已经存在'));
                            }else{
                                callback()
                            }
                        }).catch((ex)=>{
                            callback();
                        });
                      }
                    },
                    trigger: 'blur'
                }]
}`

FormItem.jsx
![image](https://user-images.githubusercontent.com/3622105/27993240-a7100360-64d8-11e7-968b-d4d4d68e8a0f.png)

**Comment by e1emeb0t** [comment]
感谢反馈, 目前`element-react`的功能移植自[element-ui](http://element.eleme.io/#/zh-CN), 暂时不支持异步验证.

**Comment by e1emeb0t** [comment]
这个问题已经在`element-react@1.0.18`中修复.
