### ISSUE TITLE
DatePicker has bug

### ISSUE THREAD

**Issue by wplnancy** [eleme/element-react#481]
### Description

Explain the issue you met, and describe what you expected to be. If you can write in English, we will be very grateful.

### Reproduce Steps

1. [First Step]
2. [Second Step]
3. [and so on...]

### Error Trace (if possible)

It's better to post up the error stack for us to trace this issue.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by e1emeb0t** [comment]
Please describe the bug you found so we can look into.
