### ISSUE TITLE
Slider onChange event not triggering

### ISSUE THREAD

**Issue by modess** [eleme/element-react#487]
`react: 15.6.1`
`element-react: 1.0.18` (tested with `1.0.17` and `1.0.16` also)

When changing the value of the Slider, the `handleDistanceChange` is never called. 

```
class Address extends Component {
  render () {
    return (
      <div>
        <Slider onChange={this.handleDistanceChange} />
      </div>
    );
  }

  handleDistanceChange = (value) => {
    console.log(value);
  }
}
```

**Comment by eschmar** [comment]
[Example not triggering the event](https://codesandbox.io/s/1joVlqXoR) on `v1.0.18`.

**Comment by matth3wga0** [comment]
Appreciate for your report, I'll look into this issue.

**Comment by modess** [comment]
Thank you for the quick response and release. However the behavior is not consistent at the moment. It works when you drag the slider, it then triggers when releasing the mouse button. But it does not work when simply clicking on the slider somewhere.

When dragging the event is also triggered multiple times often (seems to stack up). And if it triggers 4 times, the first value is often not the same as the 3 later ones which are all the same.

[Here's an updated version](https://codesandbox.io/s/1jOGYrpO3) using `v1.0.19`.

**Comment by e1emeb0t** [comment]
Thanks @modess, currently `element-react` is borrowing almost the code from [element-ui], so the code base of `Slider` is a little fuzzy, there's *value*, *inputValue*, *firstValue* and *secondValue*, that's awful, in the next couple days, I'll fix the `onChange` issue before I can make the next release.

**Comment by modess** [comment]
Thanks, works great now for a regular slider! But it [does not work for a range slider](https://codesandbox.io/s/Nk5ZK52Z8) unfortunately.

**Comment by e1emeb0t** [comment]
You can try `element-react` online, the document is not just the static show case but also an editor, I see `onChange` works as expected.

<img width="838" alt="untitled" src="https://user-images.githubusercontent.com/21698993/28308149-f6d9aa94-6bd7-11e7-874b-58f919b62c49.png">

**Comment by modess** [comment]
Yup, you're right. My bad! It works as intended when setting an initial value, thank you.
