### ISSUE TITLE
element-theme编译主题生成的css，里面有重复

### ISSUE THREAD

**Issue by GoDotDotDot** [eleme/element-react#492]
### Description

Explain the issue you met, and describe what you expected to be. If you can write in English, we will be very grateful.
当我使用`element-theme` 编译生成css样式表时，发现生成对应组件的css里面又包含了其他组件的样式表。比如`table`组件的样式表包含了`checkbox`的样式表，原因可能是table组件导入了checkbox组件。
我期望的是生成的样式表单一，只生产自己组件的样式，不要包含其他组件的样式表。

因为我目前的做法是为每个组件直接`import` 他自己的样式表，webpack在打包的时候会自动导入引用的组件的样式表，我这样做为了方便维护组件。

示例：
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Component, PropTypes } from '../../../libs';
import { enhanceColumns, calculateFixedWidth, scheduleLayout } from './mixins';
import { getScrollBarWidth } from './utils';
import TableHeader from './TableHeader';
import TableBody from './TableBody';
import TableFooter from './TableFooter';
import i18n from '../locale';

import type {
  TableProps,
  TableState,
  DefaultTableProps
} from './Types';
// 下面这句是导入的element-theme编译生成的css
import '../theme/table.css'
```

但是这个table.css文件里面包含了CheckBox的样式表，有没有办法让table.css被编译时只保留Table组件的样式表。而不用自己去手动更改table.css里面多余的其他组件的样式？

**Comment by e1emeb0t** [comment]
感谢反馈, 我看看.

**Comment by GoDotDotDot** [comment]
@e1emeb0t  是一样的，我去`element-theme-default/lib/table.css` 下看了，没有分离。同样包含了`CheckBox`这些其他组件的样式表

**Comment by e1emeb0t** [comment]
因为`element-react`并不包含css样式, 所以我建议你去[element-theme-default](https://github.com/ElementUI/theme-default)提issue.

**Comment by GoDotDotDot** [comment]
@e1emeb0t 好的，谢谢

**Comment by GoDotDotDot** [comment]
@e1emeb0t 能帮忙通告下`ElementUI` 项目组的人吗？ 我看他们的issue 响应不是太快。谢谢了

**Comment by e1emeb0t** [comment]
我试着联系一下.
