### ISSUE TITLE
popper.js update

### ISSUE THREAD

**Issue by wulucxy** [eleme/element-react#499]
### Description
目前element应用的popper.js还是0.x版本的，目前有计划升级到最新1.新版本么

**Comment by e1emeb0t** [comment]
我曾经为了兼容SSR升级到1.x的npm包, 但是会出现很多异常, 修复起来很麻烦, 所以暂时用的`element-ui`中的[popper.js](https://github.com/ElemeFE/element/blob/dev/src/utils/popper.js).
