### ISSUE TITLE
ColorPicker ok button bug with Form component

### ISSUE THREAD

**Issue by munkh-altai** [eleme/element-react#500]
When i use color picker in Form 

Select color then click ok button Form submit working.

i was try change button to a it is fine.

#ES5 original code
 _react2.default.createElement(
              'button',
              {
          
                className: 'el-color-dropdown__btn',
                onClick: function onClick() {
                  return onPick();
                }
              },
              _locale2.default.t('el.colorpicker.confirm')
            )
#ES5 changed code
 _react2.default.createElement(
              'a',
              {
                  href: 'JavaScript:',
                className: 'el-color-dropdown__btn',
                onClick: function onClick() {
                  return onPick();
                }
              },
              _locale2.default.t('el.colorpicker.confirm')
            )

**Comment by e1emeb0t** [comment]
I'm guessing you want to change the internal implement of `<button>` to `<a>`, it doesn't make sense.

**Comment by munkh-altai** [comment]
please test Form & Color Picker.
when click Color-Picker's ok button page reloading (I think this is firing to Form submit)

**Comment by e1emeb0t** [comment]
**Color Picker**: no page reloading,
**Form**: reloading when the Button `nativeType="submit"`, it's not issue just usage show case.

<img width="516" alt="wx20170725-100812 2x" src="https://user-images.githubusercontent.com/21698993/28552436-f9452986-7120-11e7-89a0-b932304b254c.png">
