### ISSUE TITLE
date & time picker validation rule's trigger not working after with FORM

### ISSUE THREAD

**Issue by munkh-altai** [eleme/element-react#501]
date & time picker validation rule's trigger not working after with FORM

Please check your validation demo. 
1. Click Submit button => show validation message
2. Select date => not remove validation massage
3. Click Submit button => removing validation massage of date picker

**Comment by e1emeb0t** [comment]
The issue is related to `onChange` attribute is only applicable to form field elements, I think **DatePicker** should have an `<input type="hidden" />` to bubble the change event, any ideas? @inter-action
