### ISSUE TITLE
popover issue.

### ISSUE THREAD

**Issue by cyyyu** [eleme/element-react#514]
### Description

Using popover in a table. the layer is too low which means half of contents are covered by table. Also it expands the height of table.
i think this should be issue on popover.
<img width="420" alt="wx20170725-154828 2x" src="https://user-images.githubusercontent.com/15100664/28561567-8da5314a-7151-11e7-87e1-947571515dd0.png">

In addition, i noticed that the popover node is located inside table node, which doesn't make sense for me. From my understanding, use something like [react-portal](https://github.com/tajo/react-portal) to build popover, tooltip..etc makes more sense for these React components.

**Comment by e1emeb0t** [comment]
This is a long term issue related to popper.js, we need replace the bundled popper.js with the npm package.

**Comment by wangbo201308** [comment]
I also encountered the problem recently, and maybe I must write a component instead for the reason that the update frequency of element-react is too slow.
