### ISSUE TITLE
InputNumber：清空后变为0

### ISSUE THREAD

**Issue by wpj-wpj-wpj** [eleme/element-react#532]
### Description

如果没有设置value属性，就没有这个问题。
设置了value属性后，通过onChange改变value的值，清空时传 '' 给value，会被Number(props.value)转换为0 

### Solution
```js
  componentWillReceiveProps(props: Object) {
    if (props.value != this.props.value) {
      this.setState({ value:  Number(props.value) });
    }
  }
```
改为
```js
  componentWillReceiveProps(props: Object) {
    if (props.value != this.props.value) {
      this.setState({ value: value==='' ? '' : Number(props.value) });
    }
  }
```

**Comment by e1emeb0t** [comment]
`InputNumber`的`value`类型是number, 所以props.value不能是空字符串. 当清空时, 我觉得还是禁用增减按钮是合理的.

**Comment by wpj-wpj-wpj** [comment]
禁用增减按钮不能解决上边的问题，即使禁用了，清空时传给onChange的value 仍是''，然后prop.value接收的值仍是''。
我觉得清空有它的应用场景，比如查询条件中表示某个字段的取值范围时，清空代表无上限或无下限。这时候如果不传''，而是传0或其他数字的话就很僵硬了

**Comment by e1emeb0t** [comment]
我之前的commit, 如果清空界面上显示空白的值而不是0, 同时`onChange`事件回调的是`undefined`, 因为此时并没有value, 所以禁用了增减按钮.

**Comment by wpj-wpj-wpj** [comment]
好吧，最初只是觉得点击增减号在清空后加减会出现在取值范围外的数 #509 ，需要额外在组件外部修正这个值很麻烦。
前两次修改虽然避免了这个bug（清空后不可点击），但是失去了一个小功能（清空后不可点击），个人感觉从体验上看有更好的解决方法才自己提交了个版本。

**Comment by e1emeb0t** [comment]
我看了一下antd和element-ui的InputNumber, 在清空后点击增减按钮后的行为都比较奇怪

**Comment by wpj-wpj-wpj** [comment]
跟着去看了一下，element-ui不能清空，清空后会回退成清空前的值。
antd支持清空，清空后增减按钮都可用，点击效果一致--如果min > 0 则变为min，如果max < 0 ，则变为max，我的想法跟antd比较接近
