### ISSUE TITLE
Select don't show selected value on first render

### ISSUE THREAD

**Issue by kascote** [eleme/element-react#536]
### Description

When the component start, I had a value that want to show as selected but it don't show, only display the place holder text.

### Reproduce Steps

```
...
this.state = {
  form: {
     ...
     time_zone: 'America/Denver',
     ...
  }
}
...

<Form.Item label="Time Zone" prop="time_zone">
  <Select value={ this.state.form.time_zone } size="large" onChange={ this.onChange.bind(this, 'time_zone') }>
   { this.state.timezones.map((tz) => {
     //console.warn('xx', tz[1], tz[1] === this.state.form.time_zone)
     return <Select.Option key={tz[1]} label={tz[0]} value={tz[1]} selected={ tz[1] === this.state.form.time_zone } />
   })}
  </Select>
</Form.Item>
```
### Error Trace (if possible)
no errors 

### Solution

I don't see a way to show the selected value when on the component first render. There is some way ?

### Additional Information

using element-react 1.1.3

**Comment by e1emeb0t** [comment]
First, `Select.Option` doesn't have a property named `selected`. The selection state is maintained by if `Select.Option.value` is equal to `Select.value`.

I can't see `this.state.timezones`, so it's hard to reproduce this issue.

**Comment by kascote** [comment]
I was digging into this and the problem seems to be this:

- when the page load, the page component receive the form data as properties (with data)
- on the page's componentDidMount, fetch the timezone data
- on the first page render, the form is populated with data (except the select)
- when the fetch on componentDidMount finish and update the state, the select options are rendered
- the selected option defined in Select.value isn't matched

if I skip the first render (when the timezones is empty) all work ok, when the componentDidMount fetch finish, timezones data is rendered ok, and the Select pick the correct selected one.

BTW: Select.Option has a `selected`prop: https://github.com/eleme/element-react/blob/master/src/select/Option.jsx#L129

**Comment by e1emeb0t** [comment]
Can you edit this file at line 239 to see if your problem been solved?

```
/path/to/project/node_modules/element-react/dist/npm/es5/src/select/Select.js
```

Change

```js
if (_selected) {
  this.state.selectedLabel = _selected.props.label;
}
```

to 

```js
if (_selected) {
  this.state.selectedLabel = _selected.props.label || _selected.props.value;
}
```

**Comment by kascote** [comment]
No, don't work either. When Select is rendered, Options is empty and the filter at Select.js:235 returns empty. 
On my case when the fetch on ComponentDidMount finish and bring the values for the Select, it was already rendered and isn't updated.

**Comment by kascote** [comment]
I saw that the examples pages have 'live' components.. I tried to hack my issue and I think is working for a test example:

https://eleme.github.io/element-react/#/en-US/select
Put this code under the Basic Example:

```
constructor(props) {
  super(props);

  this.state = {
    options: [],
    value: 'Option2'
  };
  
  this.delay = this.delay.bind(this);
}

delay(t) {
   return new Promise(function(resolve) { 
       setTimeout(resolve, t)
   });
}

componentDidMount() {
  delay(1000).then(
    this.setState(() => {
      return { 
        options: [
          {
            value: 'Option1',
            label: 'Option1'
          }, {
            value: 'Option2',
            label: 'Option2'
          }, {
            value: 'Option3',
            label: 'Option3'
          }, {
            value: 'Option4',
            label: 'Option4'
          }
        ]
      }
    })
  );
}

render() {
  return (
    <Select value={this.state.value}>
      {
        this.state.options.map(el => {
          return <Select.Option key={el.value} label={el.label} value={el.value} />
        })
      }
    </Select>
  )
}

```

**Comment by e1emeb0t** [comment]
Sorry for the delay, I'm looking into this issue right now.
