### ISSUE TITLE
React & ReactDOM as peer dependencies

### ISSUE THREAD

**Issue by gnhuy91** [eleme/element-react#539]
### Description

element-react will mostly likely be used as a library in an existing react app, I would suggest using peer dependencies avoid shipping the whole react/react-dom along with element-react.

**Comment by e1emeb0t** [comment]
Since `peerDependencies` has been deprecated in NPM 3, I'll change `package.json` like this to be compatible with NPM 2.

```json
"dependencies": {
  "react": "^15.6.1",
  "react-dom": "^15.6.1"
},
"peerDependencies": {
  "react": "^15.6.1",
  "react-dom": "^15.6.1"
}
```

Ref: https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/
