### ISSUE TITLE
DatePicker mis-aligned inside Dialog

### ISSUE THREAD

**Issue by gnhuy91** [eleme/element-react#540]
### Description

When putting DatePicker inside Dialog, the popup calendar is mis-aligned.

A picture worth a thousand words:

![screen shot 2017-08-06 at 9 20 29 pm](https://user-images.githubusercontent.com/10569203/29004141-303ed9f2-7aed-11e7-8ed3-b37fb1c34823.jpg)

**Comment by inter-action** [comment]
I'll look into it when i get some time

**Comment by e1emeb0t** [comment]
Closing this issue since it will be fixed in the `element-react@1.1.9`
