### ISSUE TITLE
How can i use this with typescript?

### ISSUE THREAD

**Issue by cookcocck** [eleme/element-react#544]
### Description

I'm using react with typescript; I wonder how can i use element-react with ts + react; 

### Reproduce Steps

1. when ` import 'element-theme-default';` was added into index.tsx

2. Here comes the errors infomation ` Failed to compile
./~/_element-theme-default@1.4.1@element-theme-default/lib/index.css
Module not found: Can't resolve 'fonts/element-icons.woff?t=1472440741' in '/home/huang/Documents/react/todolist/node_modules/_element-theme-default@1.4.1@element-theme-default/lib'`

### Additional Information

By the way, my ts &react were came from https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter

**Comment by e1emeb0t** [comment]
It seems that you need `file-loader` to resolve the font files if you're using `webpack`.

```js
module: {
    rules: [
      {
        test: /\.(eot|svg|ttf|woff|woff2)(\?.+)?$/,
        loader : 'file-loader'
      }
    ]
}

**Comment by cookcocck** [comment]
@e1emeb0
thank you for your response, I'm beg  your pardon for my poor English. I found solution which was same to your response and now `Element-react` works welll with my project, anyway, thank you for you help.

**Comment by e1emeb0t** [comment]
That's great.

**Comment by ZhijianZhang** [comment]
这个问题又出现了，而且按照大佬您说的配置 file-loader 之后还是报这样的错误。不知道关闭的issue能不能继续提问
