### ISSUE TITLE
Could not get the default value in the Select

### ISSUE THREAD

**Issue by DAVIDFlavien** [eleme/element-react#545]
### Description

Using the `Select` component I could not get the default value displayed.

### Reproduce Steps

Here is a sample of my code

```javascript
constructor(props) {
  super(props);
  this.state = {
    groups: [{
      _id: 'id',
      name: 'Default'
    }]
  };
}

render() {
  return (
    <Select disabled={ !this.state.editMode } options={ this.state.groups } value={ user.groupId ? 
      user.groupId.name : null } placeholder="Group" onChange={ this.onGroupChange }>
      {
        this.state.groups.map(el => {
           return <Select.Option key={el._id} label={el.name} value={el} />
        })
       }
    </Select>
  );
}
```

### Solution

It looks like there is no way to display a default selected value, I checked the code the of the component and we must find a way to give the options to adapt this condition.

```javascript
const selected = options.filter(option => {
         return option.props.value === value
       })[0];

       if (selected) {
         this.state.selectedLabel = selected.props.label || selected.props.value;
       }
    }
```

Best,

**Comment by e1emeb0t** [comment]
If `Select.value` match one of the `Select.Option.value`, then display `Select.value` as the default value.

In your case, you need change `Select.Option.value` to the exactly `string` instead of the `object`, the value should be `el.name` to match `user.groupId.name` I guess.

**Comment by DAVIDFlavien** [comment]
Thanks it was related, but the thing is that value must be a string an not an object...

**Comment by e1emeb0t** [comment]
Yes, `Select` currently compares values with the `===` operator, maybe we can improve this.
