### ISSUE TITLE
DatePicker 键盘支持?

### ISSUE THREAD

**Issue by jiangyijie27** [eleme/element-react#548]
是否考虑加入键盘上下左右，回车以选择？

我看了下 [ant](https://ant.design/components/date-picker-cn/) 是做了的。

---

我自己试了下在外层监听 keydown，然后 `date.setTime()` 没有问题，
不过 **键盘支持** 能封装到组件里就更好了。

**Comment by e1emeb0t** [comment]
目前`element-react`与`element-ui`保持一致, 鉴于`element-ui`还不支持按键绑定, 我先把这个issue设为enhancement.
