### ISSUE TITLE
Passing additional className for every component

### ISSUE THREAD

**Issue by silviomoreto** [eleme/element-react#554]
I would like to add other classes to the element-react components.
Is there a way to pass additional `className` for a element component such as can be done in react-bootstrap?

**Comment by e1emeb0t** [comment]
Currently most of the components should support properties such as `className` and `style`.

**Comment by silviomoreto** [comment]
I think Button and Input does not have this feature implemented.
Since this should be done for any component, I will create a pull request implementing that.
