### ISSUE TITLE
为什么一直会报Only a ReactOwner can have refs,这个错误

### ISSUE THREAD

**Issue by yangjjfc** [eleme/element-react#560]
×
赋值了文档上的几个例子,都会出现这个错误
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by e1emeb0t** [comment]
> you have multiple copies of React loaded

看一下你项目中的`node_modules`是否存在多个`react`, 通常情况这是环境配置的问题, 并不是`element-react`的.

**Comment by yangjjfc** [comment]
+-- element-react@1.1.7
| `-- react@15.6.1  deduped
`-- react@15.6.1
恩,查看有2个,非常感谢,已解决问题!!

**Comment by uu-myheart** [comment]
我是用create-react-app这个工具开发，调用<Input />时候报这个错误

**Comment by zhiyingzzhou** [comment]
@uu-myheart 删除node_modules目录，重新安装依赖就可以了,应该是冲突了
