### ISSUE TITLE
Tree组件的expandOnClickNode在设置的load方法后，不起作用。

### ISSUE THREAD

**Issue by CrisLi** [eleme/element-react#562]
### Description

期待的是将`expandOnClickNode={false}`设置后Tree只有在点击`箭头`的时候才展开，关闭子Tree。但现在是和没设置的这个属性同样的效果。

### Reproduce Steps

1. 在Tree组件上同时设置`load`方法和`expandOnClickNode={false}`
2. 点击Node节点

### Error Trace (if possible)

None

### Solution

None

### Additional Information

None

**Comment by inter-action** [comment]
这个问题我并没有重现出来, 我在加了 expandOnClickNode={false} 属性之后不点箭头 tree 节点是没法expand的，你能否再看下

**Comment by CrisLi** [comment]
@inter-action 
在最新版的code里没有这个问题了，多谢。
