### ISSUE TITLE
建议将Input的name属性返回给onChange事件。

### ISSUE THREAD

**Issue by CrisLi** [eleme/element-react#563]
按照官方文档的栗子，Input要想获得Name和Value需要每次bind一个新的onChange函数。建议参照大多数React Form组件的做法，默认将name属性传回给onChange事件，这样就不用每次都bind新函数了。

例如:
```jsx
<Input value={this.state.form.name} onChange={this.onChange.bind(this, 'name')} />
```
这个其实是React官方不推荐的做法，因为每次组件调用render方法的时候，都产生了一个新onChange函数。建议在构造器里做`this.onChange = this.onChange.bind(this);`

如果有name属性传回给onChange事件，则代码可以变为：
```jsx
<Input value={this.state.form.name} onChange={this.onChange} name="name" />
```

**Comment by e1emeb0t** [comment]
你可以在constructor里声明一个变量指向`this.onChange.bind(this, 'name')`, 为什么不修改`onChange`的返回值, 是因为`element-react`的实现要尽可能与`element-ui`保持一致.

**Comment by CrisLi** [comment]
@e1emeb0t 在`constructor`里声明变量`this.onChange.bind(this, 'name')`，如果form有很多需要提交的，需要每个Input都声明一个onChange，这样有大量的重复代码。`element-ui`是Vue的类库，应该是有双向绑定或者别的技术实现此功能吧。

**Comment by e1emeb0t** [comment]
我们只提供基础的组件, 如果这些组件不能满足你的需求, 你可以去继承重写它, 比如Input.onChange事件.

**Comment by BH-NOTHING** [comment]
@e1emeb0t 试过vue继承重写，是完全Ok的，但是用extends方法继承react组件，state,methods这些都没继承过去~很疑惑啊，具体怎么继承重写element的react组件呢
