### ISSUE TITLE
建议添加List组件

### ISSUE THREAD

**Issue by CrisLi** [eleme/element-react#564]
List组件对于任何一个WebApp都是常见的，建议添加一个样式统一的List组件。可能会涉及到修改theme代码，如果issue提在这里不合适，请挪走。可以参照[semantic-ui](https://react.semantic-ui.com/elements/list)的样式。

希望Element-react越来越好。

**Comment by e1emeb0t** [comment]
你可以在[element-ui](https://elementui.github.io/issue-generator)里提feature request, 然后我们会同步到`element-react`里.
