### ISSUE TITLE
羞涩的问下，table 里面的行操作按钮，点击时候怎么获取当前行的数据？

### ISSUE THREAD

**Issue by Liu-Biao** [eleme/element-react#578]
render: function(){
		          return (
		            <span>
		            <Dia1 />
		            
		             <Button  type="danger" size="small" onClick={self.del}>删除</Button>
		            </span>
		          )
		        }

render 里面能穿参数吗？

**Comment by sam019** [comment]
render的第一个参数即为当前行的数据，详见文档

**Comment by rainbowMorelhahahah** [comment]
解决了嘛？

**Comment by bboy-xp** [comment]
同样的疑问，没弄明白怎么传参数
