### ISSUE TITLE
ajax获取table的表头columns，数据改了，但表头不更新

### ISSUE THREAD

**Issue by lokve** [eleme/element-react#580]
`getHeader() {

    return getDataHeader().then(({data}) => {
      if (data.result.success) {
        let columns = [];
        data.content.map(v => {
          columns.push({
            // showOverflowTooltip: true,
            minWidth: v[0].length * 22 + 60 + 'px',
            prop: v[1],
            label: v[0]
          })
        })
        this.setState({
          columns
        })
        this.forceUpdate();
        console.log(this.state.columns)
      }
    })
  }
`
columns有值，但表头没有重新渲染

`
{minWidth: "104px", prop: "status", label: "状态"},
{minWidth: "104px", prop: "department_name", label: "部门"},
{minWidth: "104px", prop: "employee_name", label: "姓名"},
{minWidth: "82px", prop: "year", label: "年"}
`

求解

**Comment by e1emeb0t** [comment]
Table组件正在重写, 希望能修复此问题.
