### ISSUE TITLE
Number组件在min=200时很难输入1000

### ISSUE THREAD

**Issue by wpj-wpj-wpj** [eleme/element-react#582]
### Description
刚输入1没等按0就变成200了

**Comment by e1emeb0t** [comment]
可以适当增加这个300ms的延迟, 你觉得多少会合适呢?

https://github.com/eleme/element-react/blob/888f07e6509819736ff265a5cf9f28cfe904d861/src/input-number/InputNumber.jsx#L71

**Comment by wpj-wpj-wpj** [comment]
试了试，1000ms挺好的

**Comment by mytharcher** [comment]
这个修改引出了另一个 BUG，有延迟且延迟时间较长的时候，当快速输入完数字（或清空）且移去焦点以后（其实非常常见，比如输入完就按 `TAB`），如果验证规则里有`required`，则该次验证不会被触发。

建议`min`和`max`的规则不要在输入组件内`onInput`事件里验证且自动改值，而应该交由`FormItem`常规的验证过程。且在文档中提示使用者此规则不适用于`change`触发。
