### ISSUE TITLE
DatePicker 选择年切换年份不能正确显示

### ISSUE THREAD

**Issue by GoDotDotDot** [eleme/element-react#587]
### Description

DatePicker 当我选择面板上的年份，切换年份时，返回的结果依然是之前的旧数据。下面是gif图片，寻求能否给个解决方案。

![kapture 2017-09-21 at 11 09 09](https://user-images.githubusercontent.com/18232635/30677366-f84be59a-9ebd-11e7-8e63-b1c509e67b6f.gif)

**Comment by GoDotDotDot** [comment]
@e1emeb0t 能帮忙解决下吗？

**Comment by inter-action** [comment]
我今天把这个问题修复下
