### ISSUE TITLE
Table 宽度无法响应浏览器的宽度

### ISSUE THREAD

**Issue by xunjianxiang** [eleme/element-react#594]
如果我的浏览器宽度为1200px，里面有一个宽度百分百的表格，然后我将浏览器宽度调整为1600px，表格宽度仍然为1200px。

反之，如果浏览器初始化宽度为1600px, 里面有一个宽度百分百的表格，然后我将浏览器调整为1200px，表格宽度仍然为1600px。

究其原因，我看到表格在初始化之后会指定一个宽度，不知道出于什么原因考虑会给表格指定宽度？

**Comment by sam019** [comment]
这个BUG应该会在即将发布1.3.0版本中修复:)
