### ISSUE TITLE
DatePicker: 日期显示错误。

### ISSUE THREAD

**Issue by jiangyijie27** [eleme/element-react#595]
![image](https://user-images.githubusercontent.com/7429808/30850310-a89c296a-a2d7-11e7-86b7-0162c8ff8cad.png)

9月不应存在 31 - 37 号。

---

截图来源于 [官方文档](https://eleme.github.io/element-react/#/zh-CN/date-picker)。

**Comment by inter-action** [comment]
这个问题应该是解决过了
