### ISSUE TITLE
使用Tabs组件报错

### ISSUE THREAD

**Issue by waterflier** [eleme/element-react#605]
### Description
使用create-react-app脚手架创建一个空应用，只使用Tabs组件，运行报错：

Element ref was specified as a string (navScroll) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

### Reproduce Steps

1. 使用create-react-app创建一个新工程
2. 按文档加入代码,App.js修改后如下
```
import React, { Component } from 'react';
import './App.css';
import {Button,Icon,Tabs} from 'element-react';
import 'element-theme-default';


class App extends React.Component {
    render() {
        return (
          <Tabs activeName="2" onTabClick={ (tab) => console.log(tab.props.name) }>
            <Tabs.Pane label="用户管理" name="1">用户管理</Tabs.Pane>
            <Tabs.Pane label="配置管理" name="2">配置管理</Tabs.Pane>
            <Tabs.Pane label="角色管理" name="3">角色管理</Tabs.Pane>
            <Tabs.Pane label="定时补偿任务" name="4">定时补偿任务</Tabs.Pane>
          </Tabs>
        )
    }
}

export default App;
```
### Error Trace 

×
Element ref was specified as a string (navScroll) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
▼ 23 stack frames were expanded.
invariant
node_modules/fbjs/lib/invariant.js:42
coerceRef
node_modules/react-dom/cjs/react-dom.development.js:8579
createChild
node_modules/react-dom/cjs/react-dom.development.js:8833
reconcileChildrenArray
node_modules/react-dom/cjs/react-dom.development.js:9132
reconcileChildFibers
node_modules/react-dom/cjs/react-dom.development.js:9495
reconcileChildrenAtPriority
node_modules/react-dom/cjs/react-dom.development.js:10127
reconcileChildren
node_modules/react-dom/cjs/react-dom.development.js:10118
updateHostComponent
node_modules/react-dom/cjs/react-dom.development.js:10370
beginWork
node_modules/react-dom/cjs/react-dom.development.js:10609
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:12573
workLoop
node_modules/react-dom/cjs/react-dom.development.js:12682
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:1299
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:1338
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:1195
performWork
node_modules/react-dom/cjs/react-dom.development.js:12800
scheduleUpdateImpl
node_modules/react-dom/cjs/react-dom.development.js:13185
scheduleUpdate
node_modules/react-dom/cjs/react-dom.development.js:13124
scheduleTopLevelUpdate
node_modules/react-dom/cjs/react-dom.development.js:13395
updateContainer
node_modules/react-dom/cjs/react-dom.development.js:13425
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:17105
unbatchedUpdates
node_modules/react-dom/cjs/react-dom.development.js:13256
renderSubtreeIntoContainer
node_modules/react-dom/cjs/react-dom.development.js:17104
render
node_modules/react-dom/cjs/react-dom.development.js:17129
▲ 23 stack frames were expanded.
./src/index.js
src/index.js:7
   4 | import App from './App';
   5 | import registerServiceWorker from './registerServiceWorker';
   6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
   8 | registerServiceWorker();
   9 | 
  10 | 
View compiled
▼ 6 stack frames were expanded.
__webpack_require__
/Users/waterflier/Dropbox/Project/bucky_cloud/tools/log_webtool/webpack/bootstrap bf6af4640ab831f283e2:669
fn
/Users/waterflier/Dropbox/Project/bucky_cloud/tools/log_webtool/webpack/bootstrap bf6af4640ab831f283e2:87
0
http://localhost:3000/static/js/bundle.js:121861:18
__webpack_require__
/Users/waterflier/Dropbox/Project/bucky_cloud/tools/log_webtool/webpack/bootstrap bf6af4640ab831f283e2:669
(anonymous function)
/Users/waterflier/Dropbox/Project/bucky_cloud/tools/log_webtool/webpack/bootstrap bf6af4640ab831f283e2:715
(anonymous function)
http://localhost:3000/static/js/bundle.js:719:10
▲ 6 stack frames were expanded.

**Comment by gushiaoke** [comment]
删掉element-react下面的node_modules

**Comment by fantasy9830** [comment]
Input组件也是一样，好像从React 16.0.0+开始这样

![input](https://user-images.githubusercontent.com/26753959/31426177-d5713aca-ae94-11e7-9e4f-7f891c2b242a.PNG)

**Comment by e1emeb0t** [comment]
目前还不兼容react@16😅

**Comment by yurizhang** [comment]
"element-react@1.3.0" has incorrect peer dependency "react@^15.6.1".

**Comment by e1emeb0t** [comment]
`element-react` doesn't support react@16 right now.

**Comment by e1emeb0t** [comment]
请升级到`element-react@1.4.1`试试看, 暂时先关闭这个issue, 有问题随时可以重新打开.
