### ISSUE TITLE
I can't clear the filter input text for the Select component

### ISSUE THREAD

**Issue by saadshahd** [eleme/element-react#614]
### Description
I can't clear the filter input text for the Select component https://eleme.github.io/element-react/#/en-US/select#option-filtering 

### Reproduce Steps

1. On Select component, use the filterable option  
2. Select an option 
3. on change I can't clear the filtering input to show the whole options list again.

I want the filter input to have the option to be controlled. Thanks in advance.

**Comment by e1emeb0t** [comment]
You can try `clearable={true}` with Select component.

**Comment by saadshahd** [comment]
I tried that but it makes no difference, I had to ref the component and invoke the delete method passing a mocked Event to it.

**Comment by e1emeb0t** [comment]
I applied `clearable` to Select on https://eleme.github.io/element-react/#/en-US/select, here it is.
![oct-17-2017 10-36-46](https://user-images.githubusercontent.com/21698993/31644127-038b14f8-b327-11e7-8d00-fcc8b4384edf.gif)

BTW, you can edit the example code on the site to make live run.

**Comment by saadshahd** [comment]
I would like to clear onSelect not after clicking the clear button

**Comment by e1emeb0t** [comment]
Currently it's not supported.

**Comment by saadshahd** [comment]
Thanks a lot
