### ISSUE TITLE
ts引入Form，类型问题

### ISSUE THREAD

**Issue by curlsli** [eleme/element-react#623]
`this.refs.form.validate((valid: any) => {
            if (valid) {
                alert('submit!');
            } else {
                console.log('error submit!!');
                return false;
            }
        });`

error TS2339: Property 'validate' does not exist on type 'ReactInstance'.
  Property 'validate' does not exist on type 'Element'.

**Comment by e1emeb0t** [comment]
@inter-action 能帮忙看一下typescript的类型么?

**Comment by curlsli** [comment]
![image](https://user-images.githubusercontent.com/3116382/32104856-ce7fba68-bb58-11e7-8407-62ca3b35dd19.png)
![image](https://user-images.githubusercontent.com/3116382/32104870-de322a2c-bb58-11e7-9115-3ad93afdb909.png)

**Comment by inter-action** [comment]
这个你先强制吧 refs.form 转换成 any 吧，字符串 ref="xx" 这种方式拿到的 type 就是 ReactInstance 这样的基类，ref={(e)=>this.refs.form=e} 这种方式看看可以么，不可以的话，我等着看有没有什么解决方案

**Comment by curlsli** [comment]
@inter-action , tks ， 强制类型ok的。下边定义ref的方法会有一些问题。
