### ISSUE TITLE
警告问题：isMounted(...) is deprecated in plain JavaScript React classes.

### ISSUE THREAD

**Issue by thbgh** [eleme/element-react#637]
使用了表格组件后，控制台连续警告：isMounted(...) is deprecated in plain JavaScript React classes.
![image](https://user-images.githubusercontent.com/9399517/32100824-f578df2a-bb47-11e7-93f9-ce736c2f5b81.png)

![image](https://user-images.githubusercontent.com/9399517/32100695-591f3e30-bb47-11e7-90e2-e5755e4ade2b.png)

**Comment by sam019** [comment]
不影响使用的，暂时可以忽略，会在下一版中修复

**Comment by e1emeb0t** [comment]
请升级到`element-react@1.4.1`试试看, 暂时先关闭这个issue, 有问题随时可以重新打开.
