### ISSUE TITLE
组件问题：element-react没有Container 布局容器

### ISSUE THREAD

**Issue by thbgh** [eleme/element-react#638]
element-react没有Container 布局容器，我在写首页时比较麻烦。
看到element-Vue有那么完备的组件，很心疼react.
请问近期可以增加吗？
向你们辛苦的工作致以谢意！

![image](https://user-images.githubusercontent.com/9399517/32103209-f623eef6-bb51-11e7-97ef-fbe51340f4a6.png)

**Comment by e1emeb0t** [comment]
element-react是基于element-ui@1.x的, 暂时应该还没有计划兼容2.x.
