### ISSUE TITLE
tree defaultCheckedKeys

### ISSUE THREAD

**Issue by ChaoyaoYe** [eleme/element-react#647]
### Description

【tree】组件  —— 【defaultCheckedKeys】默认选中的值，如果在满足以下条件的时候：
1、tree为3级或3级以上的结构
2、默认选中的只有一个   且  为最底层的那一个  且  没有兄弟元素；

第一次点击，会没反应，要点击3次，才容易看出反应；

### Reproduce Steps

1. 引用tree组件，我用的是3级机构的
2. 默认选中的选项为最后一级结构   且   没有兄弟元素
3. 点击底层的一级默认选中的选项没反应   需要点击3次才看的出反应

**Comment by inter-action** [comment]
#650 应该解决掉了这个问题
