### ISSUE TITLE
Element ref was specified as a string (input) but no owner was set. You may have multiple copies of React loaded

### ISSUE THREAD

**Issue by aflext** [eleme/element-react#656]
Input 调用组件出错。由于旧版本在mac下编译出现问题，导致element-react/dist/npm/es5中的require没有被编译，找不到报错。所以升级了react(^16.1.1)、react-dom(16.1.1)、element-react(1.4.1)，跑起来后，浏览器报错。

![image](https://user-images.githubusercontent.com/3211461/32893372-cf62b3b8-ca9e-11e7-88b0-5c25064b0d9c.png)

>"webpack": "^2.6.0"
"babel-polyfill": "^6.23.0",
"babel-core": "^6.25.0",
"babel-eslint": "^7.2.3",
 "babel-loader": "^7.1.0",
node: v9.2.0

[https://github.com/eleme/element-react/issues/626](https://github.com/eleme/element-react/issues/626)

**Comment by aflext** [comment]
恢复 React和React-dom的版本到 16.0.0解决了

**Comment by clay-chen** [comment]
请教，我也遇到这个错误了，到底是那点不兼容造成的。
Element ref was specified as a string (submenu-title) but no owner was set. react^16.2.0 react-dom^16.2.0。
