### ISSUE TITLE
展开行 类型的 表格，在展开时，控制台给出了warning

### ISSUE THREAD

**Issue by forever1910** [eleme/element-react#680]
### Description

使用展开行，即：
columns: [
      {
        type: 'expand',

设定为expand时，react给出了
index.js:2177 Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in tbody (created by TableBody)
    in table (created by TableBody)
    in TableBody (created by Table)
    in div (created by Table)
    in div (created by Table)
    in Table (created by TableLayout)
    in TableLayout (created by TableStore)
    in TableStore (at Table.js:80)

这样的报错。

react版本为16.0，目测是Table里需要设置key的地方，没有设置

**Comment by sam019** [comment]
升级下element-react试试
