### ISSUE TITLE
关于Table列动态显示的问题

### ISSUE THREAD

**Issue by cooliean** [eleme/element-react#685]
### Description

那个大神可以给我说个办法呢？Vue的版本可以用v-if来做，不知道React 版本怎么动态显示某列呢，因为现在列我看到例子都是在State里面已经定义了。难道真的要写个方法来移除表头数据？

**Comment by sam019** [comment]
可以通过setState来设置新的列啊，但要确保新的列引用也是新的（不要直接对原先列的数组进行修改，因为相同的引用不会引起更新）

**Comment by cooliean** [comment]
谢谢，
