### ISSUE TITLE
我在【import 'element-theme-default';】后出错了。求教，谢谢。

### ISSUE THREAD

**Issue by gonghongchen** [eleme/element-react#718]
我在【import 'element-theme-default';】后， 用webpack打包就出现了这样的错误：
`./node_modules/element-theme-default/lib/index.css
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve 'fonts/element-icons.ttf?t=1472440741' `

【webpack.config.js】中的部分配置是：
`	module: {
		rules: [{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: "style-loader",
					use: [{
							loader: "css-loader",
							options: {
								modules: true,
								minimize: true,
								localIdentName: "[name]-[local]"	//rename class
							}
						},
						{
							loader: "postcss-loader",
							options: {
								plugins: [
									require('autoprefixer')
								]
							}
						}
					]
				})
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: [{
						loader: "babel-loader",
						options: {
							presets: ["env", "react"]
						}
					}
				]
				
			},
			{
				test: /\.(ttf|eot|svg|woff|woff2)(\?.+)?$/,
				loader: 'file-loader?name=[hash:12].[ext]'
			}
			// {
			// 	test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
			// 	use: [{
			// 		loader: 'url-loader',
			// 		options: {
			// 			limit: 10000
			// 		}
			// 	}]
			// }
		]
	},`

请问大概是由于什么原因导致的呢？谢谢哦。

你们的【element-react】做的很棒，第一次用，谢谢你们啊。

**Comment by sam019** [comment]
确定通过npm install 安装 element-theme-default了吗

**Comment by Jucuzzi** [comment]
我烨碰到了这个问题，不知如何解决

**Comment by sherryhhx** [comment]
ERROR in ./node_modules/element-theme-default/lib/index.css
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleParseError: Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by wolichuang** [comment]
import 'style-loader!css-loader!element-theme-default'
