### ISSUE TITLE
Warning: Can only update a mounted or mounting component. 

### ISSUE THREAD

**Issue by aflext** [eleme/element-react#742]
### Description
>"element-react": "^1.4.8"
"element-theme-default": "^1.4.4"
"react": "^16.2.0"
"react-dom": "^16.2.0"

- 使用Table和Pagination，在切换pageSize时，有警告如下。但是翻页没有警告。
- development时警告，production后没有

### Reproduce Steps

```javascript

import { Loading, Table as EleTable, Pagination } from 'element-react';

[
    <EleTable
        style={{ width: '100%' }}
        columns={columns}
        data={data}
        className={className}
        key={uuid.v1()}
    />, <Pagination
        layout="total, sizes, prev, pager, next, jumper"
        total={paginationData.total}
        pageSizes={paginationData.pageSizes}
        pageSize={paginationData.pageSize}
        currentPage={paginationData.currentPage}
        style={paginationStyle}
        key={uuid.v1()}
        onSizeChange={paginationData.sizeChangeHandler}
        onCurrentChange={paginationData.currentChangeHandler}
    />
]
```

### Error Trace (if possible)

![image](https://user-images.githubusercontent.com/3211461/37521573-2e7e6ed4-295c-11e8-9acf-e3d5a4d967e1.png)

### Solution

有没有最佳实践？或者这样写不对？

### Additional Information

猜测是select组件内部重绘了？

**Comment by sam019** [comment]
应该是key的值改变，导致react认为rerender前后Table不是同一个组件。使用React.Fragment 替换数组试试吧

**Comment by aflext** [comment]
@sam019 谢答，好奇怪现在又消失了。回头有时间看看为啥
