### ISSUE TITLE
table组件中带边框表格 列宽调整时的bug 当鼠标hover线框时 即使移除表格区域后鼠标一直呈cursor: col-resize状态，未恢复成默认状态

### ISSUE THREAD

**Issue by king-one** [eleme/element-react#762]
### Description

当鼠标hover线框时 即使移除表格区域后鼠标一直呈cursor: col-resize状态，未恢复成默认状态

### Reproduce Steps

1. [First Step]
2. [Second Step]
3. [and so on...]

### Error Trace (if possible)

It's better to post up the error stack for us to trace this issue.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sam019** [comment]
尝试升级下react-element版本，无法重现这个BUG
