### ISSUE TITLE
如何设置某个节点高亮?

### ISSUE THREAD

**Issue by mqliutie** [eleme/element-react#764]
`https://jsfiddle.net/63e696bn/1/`
这里面 `vue` 版本在 `react` 中不生效

看了下源码 

```
'is-current': treeNode.getCurrentNode() === this
```
是通过获取currentNode 来设置样式类

但是 `set` 仅在 `handleClick` 方法中 也就是只有点击才能设置  那 `currentNodeKey` 提供的意义是什么呢

**Comment by smczymz** [comment]
冒泡

**Comment by smczymz** [comment]
# **的风格的风格******
`w'is-current': treeNode.getCurrentNode() === this`
问问> ``

**Comment by smczymz** [comment]
1

**Comment by smczymz** [comment]
1

**Comment by smczymz** [comment]
# 搜索

**Comment by smczymz** [comment]
是

**Comment by smczymz** [comment]
啊

**Comment by situmeimei** [comment]
最后怎么解决的？

**Comment by mqliutie** [comment]
@situmeimei  好久没用这个了,.... 印象中通过设置ref给这个组件,  然后直接 `refs[自己设置的].方法`
通过这种方式直接调组件内部的方法. 印象中是这样
