### ISSUE TITLE
项目转移到新的所有者是什么情况？

### ISSUE THREAD

**Issue by mytharcher** [eleme/element-react#787]
以后这个项目还会继续维护么？还是说饿了么并入阿里以后 React 组件库以后也要统一用 AntD 了？

**Comment by whoby** [comment]
现在打不开了，移到哪里了？

**Comment by sam019** [comment]
开源项目在整理中，暂时可以通过 https://pruepei.github.io/element-react/ 访问

**Comment by rlog** [comment]
已经恢复了，纯属误操作。我们会继续花精力维护好这个项目，非常感谢你的关注 @mytharcher
